
import json
import argparse
import hashlib
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional
import re

# --- Configuration ---
BASE_DIR = Path(__file__).resolve().parent
DEFAULT_INPUT_GROBID = BASE_DIR / "01_run_out_v2" / "grobid_results_all.json"
DEFAULT_OUPUT_DIR = BASE_DIR / "05_llm_filtered_data"

# Helper to normalize strings for matching if needed (though paths should be exact)
def normalize_path(p: str) -> str:
    if not p:
        return ""
    return p.strip().replace("\\", "/")

def find_latest_classified_jsonl(search_dir: Path) -> Optional[Path]:
    """Find the latest classified_sections_*.jsonl file."""
    if not search_dir.exists():
        return None
    files = list(search_dir.glob("classified_sections_*.jsonl"))
    if not files:
        return None
    return max(files, key=lambda p: p.stat().st_mtime)

def load_classified_sections(path: Path) -> Dict[str, Dict[str, Any]]:
    """
    Load classified sections and build a lookup map.
    Key: (source_file, section_path) -> Classification Data Dictionary
    Loads EVERYTHING (YES and NO).
    """
    lookup = {}
    print(f"Loading classifications from: {path}")
    count = 0
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            try:
                row = json.loads(line)
                
                # Normalize keys
                src = normalize_path(row.get("source_file"))
                
                # Primary Key: section_path
                p1 = normalize_path(row.get("section_path"))
                if p1:
                    lookup[(src, p1)] = row
                    
                # Secondary Key: heading_raw (if different)
                p2 = normalize_path(row.get("heading_raw"))
                if p2 and p2 != p1:
                     # Only add if not conflicting? 
                     # If conflicting, section_path usually takes precedence. 
                     # We'll just add it as a fallback pointer to the SAME row object.
                     if (src, p2) not in lookup:
                        lookup[(src, p2)] = row
                
                count += 1
            except json.JSONDecodeError:
                continue
    print(f"Loaded {count} classification entries (entries in lookup: {len(lookup)}).")
    return lookup

def get_full_paragraphs(grobid_section: Dict[str, Any]) -> List[str]:
    """Extract full paragraphs list from a Grobid section object."""
    paras = grobid_section.get("paragraphs")
    if isinstance(paras, list):
        return [p for p in paras if isinstance(p, str)]
    if isinstance(paras, str):
        return [paras]
    # Fallback to text
    text = grobid_section.get("text")
    if text and isinstance(text, str):
        return [text]
    return []

def flatten_grobid_sections(sections: List[Dict[str, Any]], parent_path: str = "") -> List[Dict[str, Any]]:
    """
    Recursively walk Grobid sections and return a flat list.
    We need this because the classification might have been done on a flattened view.
    And we need to match 'section_path'.
    """
    flat = []
    for idx, sec in enumerate(sections):
        # Determine path (try to match logical path from 04 script)
        # 04 script logic: s.get("path") or fallback recursive path
        # We will try to rely on 'path' if present, because 04 script prefers it too.
        
        # Note: In grobid_results_all.json, sections usually have a 'path' field generated by the parser.
        # If not, we might fail to match. But usually it exists.
        
        children = sec.get("children", [])
        
        # Add current section
        flat.append(sec)
        
        # Recurse
        if children:
            flat.extend(flatten_grobid_sections(children))
            
    return flat

import csv

def main():
    parser = argparse.ArgumentParser(description="Filter Grobid JSON based on Classified Sections (YES decision)")
    parser.add_argument("--grobid_input", type=Path, default=DEFAULT_INPUT_GROBID, help="Original Grobid JSON file")
    parser.add_argument("--classified_input", type=Path, help="Path to classified_sections_*.jsonl (optional, auto-detects latest)")
    parser.add_argument("--output_dir", type=Path, default=DEFAULT_OUPUT_DIR, help="Output directory")
    
    args = parser.parse_args()
    
    # 1. Resolve Classification File
    cls_file = args.classified_input
    if not cls_file:
        # Default legacy dir for search
        # Try finding in 04_llm_classification sibling dir
        search_dir = BASE_DIR / "04_llm_classification"
        cls_file = find_latest_classified_jsonl(search_dir)
        
    if not cls_file or not cls_file.exists():
        print("Error: Could not find any classified_sections_*.jsonl file.")
        return

    # 2. Load Classifications
    # Map: (source_file, section_path) -> full_classification_object
    cls_map = load_classified_sections(cls_file)
    
    # 3. Load Grobid Data
    if not args.grobid_input.exists():
        print(f"Error: Grobid input not found at {args.grobid_input}")
        return
        
    print(f"Loading full text from: {args.grobid_input}")
    with open(args.grobid_input, "r", encoding="utf-8") as f:
        try:
            papers_data = json.load(f)
            # Handle {"papers": [...]} case if exists
            if isinstance(papers_data, dict) and "papers" in papers_data:
                papers_data = papers_data["papers"]
        except json.JSONDecodeError:
            print("Error: Failed to decode Grobid JSON.")
            return

    print(f"Processing {len(papers_data)} papers...")
    
    # Collections for outputs
    all_papers_output = []      # For llm_filtered_all_*.jsonl
    filtered_papers_kept = []   # For llm_filtered_kept_*.jsonl
    removed_sections_flat = []  # For llm_filtered_removed_*.jsonl & csv
    
    for paper in papers_data:
        source_file = normalize_path(paper.get("source_file"))
        
        # We will build lists for this specific paper
        current_paper_all_sections = []
        current_paper_kept_sections = []
        
        # Use sections_flat if available
        raw_sections = paper.get("sections", [])
        flat_sections = flatten_grobid_sections(raw_sections)
        
        relevant_count = 0
        
        for sec in flat_sections:
            sec_path = normalize_path(sec.get("path"))
            sec_heading = normalize_path(sec.get("heading"))
            
            # Try to match by path first, then heading
            key = (source_file, sec_path)
            if key not in cls_map and sec_heading:
                 key = (source_file, sec_heading)
            
            if key in cls_map:
                cls_info = cls_map[key]
                decision = cls_info.get("final_decision")
                
                # Construct the filtered section object
                relevant_sec = {
                    "heading": sec.get("heading", ""),
                    "path": sec_path,
                    "level": sec.get("level"),
                    "paragraphs": get_full_paragraphs(sec),
                    
                    # Embed Classification Meta
                    "llm_decision": decision,
                    "llm_confidence": cls_info.get("final_confidence"),
                    "llm_reason": cls_info.get("final_reason"),
                    "hit_paragraphs": cls_info.get("hit_paragraphs", []),
                    "source_file": source_file, 
                    "paper_title": paper.get("title", ""),
                    
                    "content_excerpt": cls_info.get("hit_paragraphs")[0]["snippet"] if cls_info.get("hit_paragraphs") else ""
                }
                
                # Add to flat removed list if NO
                if decision != "YES":
                    removed_sections_flat.append(relevant_sec)
                else:
                    relevant_count += 1
                    current_paper_kept_sections.append(relevant_sec)
                
                # Add to unified list (BOTH YES and NO)
                current_paper_all_sections.append(relevant_sec)
        
        # 1. Prepare Entry for ALL
        if current_paper_all_sections:
            doc_all = {
                "source_file": source_file,
                "title": paper.get("title", ""),
                "abstract_paragraphs": paper.get("abstract_paragraphs", []),
                "sections": current_paper_all_sections,
                "relevant_section_count": relevant_count
            }
            all_papers_output.append(doc_all)
            
        # 2. Prepare Entry for KEPT
        if current_paper_kept_sections:
            doc_kept = {
                "source_file": source_file,
                "title": paper.get("title", ""),
                "abstract_paragraphs": paper.get("abstract_paragraphs", []),
                "sections": current_paper_kept_sections,
                "relevant_section_count": len(current_paper_kept_sections)
            }
            filtered_papers_kept.append(doc_kept)
            
    # 4. Output
    args.output_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    # Save ALL (Unified)
    out_file_all = args.output_dir / f"llm_filtered_all_{ts}.jsonl"
    print(f"Saving {len(all_papers_output)} papers (ALL sections) to {out_file_all}...")
    with open(out_file_all, "w", encoding="utf-8") as f:
        for p in all_papers_output:
            f.write(json.dumps(p, ensure_ascii=False) + "\n")

    # Save KEPT
    out_file_kept = args.output_dir / f"llm_filtered_kept_{ts}.jsonl"
    print(f"Saving {len(filtered_papers_kept)} papers (KEPT sections only) to {out_file_kept}...")
    with open(out_file_kept, "w", encoding="utf-8") as f:
        for p in filtered_papers_kept:
            f.write(json.dumps(p, ensure_ascii=False) + "\n")
            
    # Save REMOVED (JSONL)
    out_file_removed_json = args.output_dir / f"llm_filtered_removed_{ts}.jsonl"
    print(f"Saving {len(removed_sections_flat)} removed sections to {out_file_removed_json}...")
    with open(out_file_removed_json, "w", encoding="utf-8") as f:
        for item in removed_sections_flat:
             f.write(json.dumps(item, ensure_ascii=False) + "\n")

    # Save REMOVED (CSV)
    out_file_removed_csv = args.output_dir / f"llm_filtered_removed_{ts}.csv"
    print(f"Saving REMOVED CSV to {out_file_removed_csv}...")
    with open(out_file_removed_csv, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["source_file", "heading", "decision", "reason", "confidence"])
        for item in removed_sections_flat:
            writer.writerow([
                item.get("source_file"),
                item.get("heading"),
                item.get("llm_decision"),
                item.get("llm_reason"),
                item.get("llm_confidence")
            ])
            
    print("Done.")

if __name__ == "__main__":
    main()
